Get weather
Relluem94s/RelluToolbox pull request #11
Opened 2023-08-03 21:32 UTC by dennischrispens

2023-09-12 19:40 UTC, folivora97 requested changes

2023-09-12 19:40 UTC, folivora97 commented on tools/getWeather.php
> +$apiKey = '8d292866760141758dfec6b5529f2ea5';
Never API Key in den Code schreiben :)

2023-09-12 19:40 UTC, folivora97 commented on tools/getWeather.php
> +$city = $_GET['city'];
Wir sollten den GET Parameter noch richtig escapen um eine Injection zu vermeiden :)

2023-09-12 19:40 UTC, folivora97 commented on tools/getWeather.php
> +$apiUrl = "http://api.openweathermap.org/data/2.5/weather?q=$city&lang=de&appid=$apiKey&units=metric";
Kann auch im Besten Fall in die env.php

2023-10-08 21:49 UTC, Relluem94 commented on tools/getWeather.php
> +$apiUrl = "http://api.openweathermap.org/data/2.5/weather?q=$city&lang=de&appid=$apiKey&units=metric";
ist in der .env

2023-10-08 21:50 UTC, Relluem94 commented on tools/getWeather.php
> +$city = $_GET['city'];
filter eingebaut

2023-10-08 21:52 UTC, Relluem94 approved these changes

2023-10-09 19:14 UTC, folivora97 approved these changes

2023-10-09 19:32 UTC, merged